### ISSUE TITLE
proj3.m issue

### ISSUE THREAD

**Issue by kaiqiangh** [coldmanck/Project-3-Scene-recognition-with-bag-of-words#1]
Hi coldmanck,
I just downloaded your nice codes and run proj3.m file in MATLAB. However I got error "Index exceeds matrix dimensions." from step 0. Any solution for it? Thanks a lot.

**Comment by coldmanck** [comment]
Hi @burgess666 
Can you provide more detail, like which line produces the error? Also, did you set up your own directory path to vlfeat? (line 30)

**Comment by kaiqiangh** [comment]
Hi @coldmanck 
Thanks for replying. the vlfeat version is 0.9.20. And error details are following. Thanks a lot.

>> proj3
Index exceeds matrix dimensions.

Error in get_image_paths (line 27)
       train_image_paths{(i-1)*num_train_per_cat + j} = fullfile(data_path, 'train',
       categories{i}, images(j).name);

Error in proj3 (line 56)
    get_image_paths(data_path, categories, num_train_per_cat);

**Comment by coldmanck** [comment]
Hi @burgess666 
I have checked and implemented my code again and it seems no problem to run. Please ensure your path to vlfeat (line 30) is correct. 

Installation Step:
1) Download the repo
2) Download the vlfeat-0.9.20
3) Set up path to vlfeat correctly at line 30 in proj3.m
4) Enjoy :)

**Comment by kaiqiangh** [comment]
Thanks for your suggestion. I am sure that I correctly installed vlfeat.
vl_version('VERBOSE')
VLFeat version 0.9.20
    Static config: X64, little_endian, GNU C 40201 LP64, POSIX_threads, SSE2
    8 CPU(s): GenuineIntel MMX SSE SSE2 SSE3 SSE41 SSE42 AVX
    Debug: no
    SIMD enabled: yes

I just commented line 30 in proj3.m, because I have added this to startup.m file in root directory. Then, I rerun the codes without any modifications, and got the same error as before. Is there a problem about matrix in get_image_paths function? Thanks again.

**Comment by kaiqiangh** [comment]
By the way, should each class in test dataset contain 100 images as well? There have some classes in test dataset, which contain more than 100 images.

**Comment by coldmanck** [comment]
I cannot figure out what your problem is. I can run the program normally. Did you change any other setting? What OS do you use? Also be aware of your path using `/` or `\`. You may want to change to another computer/os to try.

The number of test images per category has been set to 100 for convenience. You can modify that in `get_image_paths.m`.

**Comment by kaiqiangh** [comment]
Thanks for your information. You are very helpful. Anyway, I would try codes in different OS. Thanks again.

**Comment by coldmanck** [comment]
No problem :)
